// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/create-course.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.8";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/create-course.ts
var create_course_default = defineTool({
  name: "create_course",
  title: "Create course",
  description: "Create a new Meridian course. Requires an admin account; other users are rejected by the database.",
  inputSchema: {
    title: z.string().trim().min(1).describe("Course title, in Hebrew for player-facing content."),
    subject: z.string().trim().min(1).describe("Subject area, e.g. history, math, english."),
    description: z.string().trim().optional().describe("Short course description."),
    status: z.enum(["draft", "active"]).default("draft").describe("Publish state. Defaults to draft."),
    display_order: z.number().int().min(0).default(0).describe("Ordering position in course lists.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, subject, description, status, display_order }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("courses").insert({ title, subject, description, status: status ?? "draft", display_order: display_order ?? 0 }).select("id, title, subject, description, status, display_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { course: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_my_profile_default = defineTool2({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in Meridian player profile (email, role, created date).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, email, role, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile row found for this user." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var list_courses_default = defineTool3({
  name: "list_courses",
  title: "List courses",
  description: "List Meridian courses visible to the signed-in user, ordered by display order.",
  inputSchema: {
    status: z2.enum(["active", "draft"]).optional().describe("Filter by course status. Drafts are admin-only."),
    limit: z2.number().int().min(1).max(100).default(50).describe("Maximum number of courses to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("courses").select("id, title, description, subject, status, display_order").order("display_order", { ascending: true }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-lessons.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_lessons_default = defineTool4({
  name: "list_lessons",
  title: "List lessons",
  description: "List the lessons of one Meridian course, ordered by display order.",
  inputSchema: {
    course_id: z3.string().uuid().describe("The course whose lessons should be listed."),
    status: z3.enum(["active", "draft"]).optional().describe("Filter by lesson status. Drafts are admin-only.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("lessons").select("id, course_id, title, content, status, display_order").eq("course_id", course_id).order("display_order", { ascending: true });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { lessons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-missions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var list_missions_default = defineTool5({
  name: "list_missions",
  title: "List missions",
  description: "List the missions of one Meridian lesson, including objective, task and hints.",
  inputSchema: {
    lesson_id: z4.string().uuid().describe("The lesson whose missions should be listed."),
    status: z4.enum(["active", "draft"]).optional().describe("Filter by mission status. Drafts are admin-only.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lesson_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("missions").select(
      "id, lesson_id, title, objective, instructions, task, hint, guidance_level_1, guidance_level_2, guidance_level_3, status, display_order"
    ).eq("lesson_id", lesson_id).order("display_order", { ascending: true });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { missions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pntmkkwrxjkjaadooxpj";
var mcp_default = defineMcp({
  name: "github-sync-hub",
  title: "GitHub Sync Hub",
  version: "0.1.0",
  instructions: "Tools for the Meridian learning platform. Read the signed-in player profile, browse courses, lessons and missions, and create courses (admin only). All player-facing content is in Hebrew.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_courses_default, list_lessons_default, list_missions_default, create_course_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
